### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [krak3n/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one

Finally, please consider renaming the repo to something less generic - I won't know what to call it in the list if it's just zsh-theme.

**Comment by krak3n** [comment]
Sure, no worries 👍

**Comment by krak3n** [comment]
@unixorn added a screenshot and license, it's a really simple screenshot (for a simple theme 😛) for now, I want to record a gif and what not to better show it but anyways 😄

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/688
